<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Audio\Micser.Audio.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Micser.Plugins.Main.Tests" />
  </ItemGroup>

</Project>
