//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Micser.App.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Micser.App.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Libraries and tools used:.
        /// </summary>
        public static string AboutLibrariesTitle {
            get {
                return ResourceManager.GetString("AboutLibrariesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Micser - The managed audio routing framework..
        /// </summary>
        public static string AboutText {
            get {
                return ResourceManager.GetString("AboutText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version:.
        /// </summary>
        public static string AboutVersionText {
            get {
                return ResourceManager.GetString("AboutVersionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Micser.
        /// </summary>
        public static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export configuration to file....
        /// </summary>
        public static string ExportConfigurationDialogTitle {
            get {
                return ResourceManager.GetString("ExportConfigurationDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export settings to file....
        /// </summary>
        public static string ExportSettingsDialogTitle {
            get {
                return ResourceManager.GetString("ExportSettingsDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import configuration from file....
        /// </summary>
        public static string ImportConfigurationDialogTitle {
            get {
                return ResourceManager.GetString("ImportConfigurationDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import settings from file....
        /// </summary>
        public static string ImportSettingsDialogTitle {
            get {
                return ResourceManager.GetString("ImportSettingsDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JSON files.
        /// </summary>
        public static string JsonFiles {
            get {
                return ResourceManager.GetString("JsonFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License.
        /// </summary>
        public static string License {
            get {
                return ResourceManager.GetString("License", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _About.
        /// </summary>
        public static string MenuItemAboutHeader {
            get {
                return ResourceManager.GetString("MenuItemAboutHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for updates.
        /// </summary>
        public static string MenuItemCheckUpdateHeader {
            get {
                return ResourceManager.GetString("MenuItemCheckUpdateHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E_xit.
        /// </summary>
        public static string MenuItemExitHeader {
            get {
                return ResourceManager.GetString("MenuItemExitHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export....
        /// </summary>
        public static string MenuItemExportHeader {
            get {
                return ResourceManager.GetString("MenuItemExportHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _File.
        /// </summary>
        public static string MenuItemFileHeader {
            get {
                return ResourceManager.GetString("MenuItemFileHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Help.
        /// </summary>
        public static string MenuItemHelpHeader {
            get {
                return ResourceManager.GetString("MenuItemHelpHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Import....
        /// </summary>
        public static string MenuItemImportHeader {
            get {
                return ResourceManager.GetString("MenuItemImportHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Re_fresh.
        /// </summary>
        public static string MenuItemRefreshHeader {
            get {
                return ResourceManager.GetString("MenuItemRefreshHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Restart Audio Engine.
        /// </summary>
        public static string MenuItemRestartHeader {
            get {
                return ResourceManager.GetString("MenuItemRestartHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Save.
        /// </summary>
        public static string MenuItemSaveHeader {
            get {
                return ResourceManager.GetString("MenuItemSaveHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Settings.
        /// </summary>
        public static string MenuItemSettingsHeader {
            get {
                return ResourceManager.GetString("MenuItemSettingsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Start Audio Engine.
        /// </summary>
        public static string MenuItemStartHeader {
            get {
                return ResourceManager.GetString("MenuItemStartHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sto_p Audio Engine.
        /// </summary>
        public static string MenuItemStopHeader {
            get {
                return ResourceManager.GetString("MenuItemStopHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Tools.
        /// </summary>
        public static string MenuItemToolsHeader {
            get {
                return ResourceManager.GetString("MenuItemToolsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sets the active color theme of the user interface..
        /// </summary>
        public static string SettingColorThemeDescription {
            get {
                return ResourceManager.GetString("SettingColorThemeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color theme.
        /// </summary>
        public static string SettingColorThemeName {
            get {
                return ResourceManager.GetString("SettingColorThemeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sets the active display language..
        /// </summary>
        public static string SettingLanguageDescription {
            get {
                return ResourceManager.GetString("SettingLanguageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string SettingLanguageName {
            get {
                return ResourceManager.GetString("SettingLanguageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If enabled, the program will minimize to the system tray instead of minimizing to the task bar..
        /// </summary>
        public static string SettingMinimizeToTrayDescription {
            get {
                return ResourceManager.GetString("SettingMinimizeToTrayDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimize to tray.
        /// </summary>
        public static string SettingMinimizeToTrayName {
            get {
                return ResourceManager.GetString("SettingMinimizeToTrayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The delay to wait before starting the engine after the computer is resuming from a suspended state (sleep, hibernation). Increase this setting if you don&apos;t have audio output after the computer was suspended..
        /// </summary>
        public static string SettingResumeDelayDescription {
            get {
                return ResourceManager.GetString("SettingResumeDelayDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resume Delay (s).
        /// </summary>
        public static string SettingResumeDelayName {
            get {
                return ResourceManager.GetString("SettingResumeDelayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If enabled, the program will start when you log in..
        /// </summary>
        public static string SettingStartupDescription {
            get {
                return ResourceManager.GetString("SettingStartupDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If enabled, the program will start minimized on system startup (when &quot;Startup&quot; is enabled).
        /// </summary>
        public static string SettingStartupMinimizedDescription {
            get {
                return ResourceManager.GetString("SettingStartupMinimizedDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start minimized.
        /// </summary>
        public static string SettingStartupMinimizedName {
            get {
                return ResourceManager.GetString("SettingStartupMinimizedName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Startup.
        /// </summary>
        public static string SettingStartupName {
            get {
                return ResourceManager.GetString("SettingStartupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatically check for updates and notify when an update is ready to install..
        /// </summary>
        public static string SettingUpdateCheckDescription {
            get {
                return ResourceManager.GetString("SettingUpdateCheckDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for updates.
        /// </summary>
        public static string SettingUpdateCheckName {
            get {
                return ResourceManager.GetString("SettingUpdateCheckName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configures the number of virtual audio cables. Changing this requires administrative privileges..
        /// </summary>
        public static string SettingVacCountDescription {
            get {
                return ResourceManager.GetString("SettingVacCountDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Virtual Audio Cables.
        /// </summary>
        public static string SettingVacCountName {
            get {
                return ResourceManager.GetString("SettingVacCountName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go back.
        /// </summary>
        public static string ToolBarBackDescription {
            get {
                return ResourceManager.GetString("ToolBarBackDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string ToolBarDeleteDescription {
            get {
                return ResourceManager.GetString("ToolBarDeleteDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forward.
        /// </summary>
        public static string ToolBarForwardDescription {
            get {
                return ResourceManager.GetString("ToolBarForwardDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string ToolBarHomeDescription {
            get {
                return ResourceManager.GetString("ToolBarHomeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load.
        /// </summary>
        public static string ToolBarLoadDescription {
            get {
                return ResourceManager.GetString("ToolBarLoadDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        public static string ToolBarRefreshDescription {
            get {
                return ResourceManager.GetString("ToolBarRefreshDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string ToolBarSettingsDescription {
            get {
                return ResourceManager.GetString("ToolBarSettingsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View License.
        /// </summary>
        public static string ViewLicense {
            get {
                return ResourceManager.GetString("ViewLicense", resourceCulture);
            }
        }
    }
}
