// <auto-generated />

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Micser.DataAccess;

namespace Micser.Migrations
{
    [DbContext(typeof(EngineDbContext))]
    [Migration("20191002131038_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0");

            modelBuilder.Entity("Micser.Common.DataAccess.Models.SettingValue", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Key")
                        .HasColumnType("TEXT");

                    b.Property<string>("ValueJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("ValueType")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("Settings");
                });

            modelBuilder.Entity("Micser.Engine.Infrastructure.DataAccess.Models.Module", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ModuleType")
                        .HasColumnType("TEXT");

                    b.Property<string>("StateJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("WidgetType")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Modules");
                });

            modelBuilder.Entity("Micser.Engine.Infrastructure.DataAccess.Models.ModuleConnection", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("SourceConnectorName")
                        .HasColumnType("TEXT");

                    b.Property<long>("SourceModuleId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TargetConnectorName")
                        .HasColumnType("TEXT");

                    b.Property<long>("TargetModuleId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SourceModuleId");

                    b.HasIndex("TargetModuleId");

                    b.ToTable("ModuleConnections");
                });

            modelBuilder.Entity("Micser.Engine.Infrastructure.DataAccess.Models.ModuleConnection", b =>
                {
                    b.HasOne("Micser.Engine.Infrastructure.DataAccess.Models.Module", "SourceModule")
                        .WithMany("SourceModuleConnections")
                        .HasForeignKey("SourceModuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Micser.Engine.Infrastructure.DataAccess.Models.Module", "TargetModule")
                        .WithMany("TargetModuleConnections")
                        .HasForeignKey("TargetModuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
