// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Micser.DataAccess;

namespace Micser.Migrations
{
    [DbContext(typeof(EngineDbContext))]
    [Migration("20210114120317_Refactoring")]
    partial class Refactoring
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("Micser.DataAccess.Entities.ModuleConnectionEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("SourceConnectorName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("SourceModuleId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TargetConnectorName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("TargetModuleId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SourceModuleId");

                    b.HasIndex("TargetModuleId");

                    b.ToTable("ModuleConnections");
                });

            modelBuilder.Entity("Micser.DataAccess.Entities.ModuleEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("StateJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Modules");
                });

            modelBuilder.Entity("Micser.DataAccess.Entities.SettingValue", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ValueJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("ValueType")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("Settings");
                });

            modelBuilder.Entity("Micser.DataAccess.Entities.ModuleConnectionEntity", b =>
                {
                    b.HasOne("Micser.DataAccess.Entities.ModuleEntity", "SourceModule")
                        .WithMany("SourceModuleConnections")
                        .HasForeignKey("SourceModuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Micser.DataAccess.Entities.ModuleEntity", "TargetModule")
                        .WithMany("TargetModuleConnections")
                        .HasForeignKey("TargetModuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SourceModule");

                    b.Navigation("TargetModule");
                });

            modelBuilder.Entity("Micser.DataAccess.Entities.ModuleEntity", b =>
                {
                    b.Navigation("SourceModuleConnections");

                    b.Navigation("TargetModuleConnections");
                });
#pragma warning restore 612, 618
        }
    }
}
